#!/usr/bin/env bash

set -e
set -x

export HOME=/var/lib/forgejo

BARE_REPO=$HOME/repositories/elinvention/riichi-keisanki.git/
WORKING_DIRECTORY=/var/tmp/riichi-keisanki
PUBLIC_WWW=/srv/riichi

mkdir -p $WORKING_DIRECTORY

for branch in `env -i git -C $BARE_REPO branch --all --format='%(refname:short)'`
do
    bdir="$WORKING_DIRECTORY/$branch"
    if env -i git -C $bdir rev-parse --is-inside-work-tree
    then
        env -i git -C $bdir fetch
        env -i git -C $bdir reset --hard origin/$branch
        env -i git -C $bdir submodule update --init
    else
        rm -rf "$bdir"
        env -i git clone --recurse-submodules $BARE_REPO $bdir -b $branch
    fi
done

while read oldrev newrev refname
do
    branch=$(env -i git -C $BARE_REPO rev-parse --symbolic --abbrev-ref $refname)

    pushd "$WORKING_DIRECTORY/$branch"

    echo "Running npm install..."
    npm install
    echo "Compiling with shdow-cljs..."
    #clj -M -m cljs.main --optimizations advanced -c riichi-calc.reagent
    BUILD_SHA=${newrev:0:7} npm run build
    echo "Copying files..."
    rm -rf $PUBLIC_WWW/$branch/
    mkdir -p $PUBLIC_WWW/$branch/
    cp -rL resources/public/* $PUBLIC_WWW/$branch/

    echo -e "branch: $branch\nrev: $newrev\nbuild date: $(date)" > $PUBLIC_WWW/$branch/VERSION
    popd
done
